[package]
name = "ex"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.9.8"
volatile = "0.2.3"
bootloader = "0.9.0"
[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
##############

[profile.dev]
panic="abort"
[profile.release]
panic="abort"
